# Generated by Django 4.1.3 on 2022-12-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_follow_follow_unique_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(max_length=254, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(max_length=254, upload_to='users/'),
        ),
    ]
