# Generated by Django 4.1.3 on 2022-12-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_post_picture_alter_post_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pfp',
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/danstagram-ad70a.appspot.com/o/posts%2FAnon.png?alt=media&token=25131999-4c9d-4362-b093-dccadb402b2d'),
        ),
    ]
